//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "persons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::emails::Entity")]
    Emails,
    #[sea_orm(has_many = "super::mobiles::Entity")]
    Mobiles,
}

impl Related<super::emails::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Emails.def()
    }
}

impl Related<super::mobiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mobiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
